// apps/frontend/panel-vue/components/features/users/UserUpdate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const props = defineProps<{
  data: IUser
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.users._)
const mainStore = useMainStore()
const cachedData = ref<IUser>(props.data)
const updatedValues = ref<TUserUpdate>({})
const {
  error: uError,
  execute: uExecute,
  status: uStatus,
} = usersApi.update({
  id: props.data.id,
  fields: updatedValues,
})
const {
  error: dError,
  execute: dExecute,
  status: dStatus,
} = usersApi.delete({ items: [props.data.id] })

function updateHandler(fields: TUserUpdate) {
  updatedValues.value = getUpdatedValues<TUserUpdate>(
    cachedData.value,
    fields,
  )

  if (Object.keys(updatedValues.value).length > 0) {
    uExecute()
  }
  else {
    mainStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(uStatus, () => {
  if (uStatus.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
    cachedData.value = { ...cachedData.value, ...updatedValues.value }
  }
})

watch(uError, () => {
  if (uError.value) {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(uError.value, locale.value),
    })
  }
})

watch(dStatus, () => {
  if (dStatus.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(dError, () => {
  if (dError.value) {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(dError.value, locale.value),
    })
  }
})
</script>

<template>
  <UserForm
    update-show
    delete-show
    :initial-data="data"
    :update-disabled="!rights.updating || dStatus === 'pending' || dStatus === 'success'"
    :update-loading="uStatus === 'pending'"
    :delete-disabled="!rights.deleting || dStatus === 'success' || data.roles?.some((role) => role.admin)"
    :delete-loading="dStatus === 'pending'"
    @update="updateHandler($event)"
    @delete="dExecute()"
  />
</template>

// apps/frontend/panel-react/src/features/users/UserUpdate.tsx
import { FC, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { useAppDispatch } from "@/app/store/hooks";
import { addAlert } from "@/app/store/main/main";
import { IUser, TUserUpdate } from "@ap/shared/dist/types";
import { getErrorText, getUpdatedValues } from "@ap/shared/dist/libs";
import { UserForm } from "@/entities/user/UserForm";
import { usersApi } from "@/entities/user/api";
import { ROUTES } from "@/shared/lib/constants";

export const UserUpdate: FC<{ data: IUser; onDelete?: () => void }> = ({
  data,
  onDelete,
}) => {
  const dispatch = useAppDispatch();
  const { t, i18n } = useTranslation();
  const [update, updateReq] = usersApi.useUpdateMutation();
  const [destroy, deleteReq] = usersApi.useDeleteMutation();
  const [cachedData, setCachedData] = useState<IUser>(data);
  const rights = useRights(ROUTES.api.users._);

  const updateHandler = (fields: TUserUpdate) => {
    const updatedValues = getUpdatedValues<TUserUpdate>(cachedData, fields);

    if (Object.keys(updatedValues).length > 0) {
      update({ id: data.id, fields: updatedValues });
    } else {
      dispatch(addAlert({ type: "warning", text: t("nothingToUpdate") }));
    }
  };

  useEffect(() => {
    if (updateReq.isSuccess) {
      dispatch(addAlert({ type: "success", text: t("success") }));
      setCachedData((prev) => ({ ...prev, ...updateReq.originalArgs?.fields }));
    }
  }, [updateReq.isSuccess, updateReq.originalArgs, dispatch, t]);

  useEffect(() => {
    if (updateReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(updateReq.error, i18n.language),
        }),
      );
    }
  }, [updateReq.error, dispatch, i18n]);

  useEffect(() => {
    if (deleteReq.isSuccess) {
      dispatch(addAlert({ type: "success", text: t("success") }));
      onDelete?.();
    }
  }, [deleteReq.isSuccess, dispatch, onDelete, t]);

  useEffect(() => {
    if (deleteReq.error) {
      dispatch(
        addAlert({
          type: "error",
          text: getErrorText(deleteReq.error, i18n.language),
        }),
      );
    }
  }, [deleteReq.error, dispatch, i18n]);

  return (
    <UserForm
      initialData={data}
      onUpdate={(fields) => updateHandler(fields)}
      updateDisabled={
        !rights.updating || deleteReq.isLoading || deleteReq.isSuccess
      }
      updateLoading={updateReq.isLoading}
      onDelete={() => destroy({ items: [data.id] })}
      deleteDisabled={
        !rights.deleting ||
        deleteReq.isSuccess ||
        data.roles?.some((role) => role.admin)
      }
      deleteLoading={deleteReq.isLoading}
    />
  );
};
