// apps/frontend/panel-vue/app/components/features/users/UserRolesUpdate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const { user } = defineProps<{
  user: IUser
  roles: IRole[]
}>()

const updatedRoles = ref<IUsersRoles[]>(
  user.roles?.map(role => ({ roleId: role.id, userId: user.id })) ?? [],
)
const { t, locale } = useI18n()
const { status, error, execute } = usersApi.updateRoles({
  id: user.id,
  fields: { items: updatedRoles },
})
const alertsStore = useAlertsStore()
const rights = useRights(ROUTES.api.users._)

watch(error, () => {
  if (!error.value) {
    return
  }

  alertsStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <UserRolesForm
    :user="user"
    :roles="roles"
    :disabled="!rights.updating"
    :loading="status === 'pending'"
    @update="(newUserRoles) => {
      updatedRoles = newUserRoles
      execute()
    }"
  />
</template>

// apps/frontend/panel-react/src/features/users/UserRolesUpdate.tsx
import { FC } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { getErrorText, IRole, IUser } from "@workspace/shared";
import { UserRolesForm } from "@/entities/user/UserRolesForm";
import { useUpdateUserRolesMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const UserRolesUpdate: FC<{
  user: IUser;
  roles: IRole[];
}> = ({ user, roles }) => {
  const { t, i18n } = useTranslation();
  const updateUserRoles = useUpdateUserRolesMutation();
  const rights = useRights(ROUTES.api.users._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  return (
    <UserRolesForm
      user={user}
      roles={roles}
      onUpdate={(newUserRoles) =>
        updateUserRoles.mutate(
          { id: user.id, fields: { items: newUserRoles } },
          {
            onSuccess: () => addAlert({ type: "success", text: t("success") }),
            onError: (error) =>
              addAlert({
                type: "error",
                text: getErrorText(error, i18n.language),
              }),
          },
        )
      }
      updateDisabled={!rights.updating}
      updateLoading={updateUserRoles.isPending}
    />
  );
};
