// apps/frontend/panel-vue/app/components/features/users/UserUpdate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const props = defineProps<{
  data: IUser
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.users._)
const alertsStore = useAlertsStore()
const cachedData = ref<IUser>(props.data)
const updatedValues = ref<TUserUpdate>({})
const {
  error: uError,
  execute: uExecute,
  status: uStatus,
} = usersApi.update({
  id: props.data.id,
  fields: updatedValues,
})
const {
  error: dError,
  execute: dExecute,
  status: dStatus,
} = usersApi.delete({ items: [props.data.id] })

function handleUpdate(fields: TUserUpdate) {
  updatedValues.value = getUpdatedValues<TUserUpdate>(
    cachedData.value,
    fields,
  )

  if (Object.keys(updatedValues.value).length > 0) {
    uExecute()
  }
  else {
    alertsStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(uStatus, () => {
  if (uStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    cachedData.value = { ...cachedData.value, ...updatedValues.value }
  }
})

watch(uError, () => {
  if (uError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(uError.value, locale.value),
    })
  }
})

watch(dStatus, () => {
  if (dStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(dError, () => {
  if (dError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(dError.value, locale.value),
    })
  }
})
</script>

<template>
  <UserForm
    update-show
    delete-show
    :initial-data="data"
    :update-disabled="!rights.updating || dStatus === 'pending' || dStatus === 'success'"
    :update-loading="uStatus === 'pending'"
    :delete-disabled="!rights.deleting || dStatus === 'success' || data.roles?.some((role) => role.admin)"
    :delete-loading="dStatus === 'pending'"
    @update="handleUpdate($event)"
    @delete="dExecute()"
  />
</template>

// apps/frontend/panel-react/src/features/users/UserUpdate.tsx
import { FC, useRef } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import {
  getErrorText,
  getUpdatedValues,
  IUser,
  TUserUpdate,
} from "@workspace/shared";
import { UserForm } from "@/entities/user/UserForm";
import { useDeleteUsersMutation, useUpdateUserMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const UserUpdate: FC<{ data: IUser; onDelete?: () => void }> = ({
  data,
  onDelete,
}) => {
  const { t, i18n } = useTranslation();
  const updateUser = useUpdateUserMutation();
  const deleteUsers = useDeleteUsersMutation();
  const cachedData = useRef(data);
  const rights = useRights(ROUTES.api.users._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleUpdate = (fields: TUserUpdate) => {
    const updatedValues = getUpdatedValues<TUserUpdate>(
      cachedData.current,
      fields,
    );

    if (Object.keys(updatedValues).length === 0) {
      addAlert({ type: "warning", text: t("nothingToUpdate") });
      return;
    }

    updateUser.mutate(
      { id: data.id, fields: updatedValues },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          cachedData.current = { ...cachedData.current, ...updatedValues };
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  const handleDelete = () => {
    deleteUsers.mutate(
      { items: [data.id] },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          onDelete?.();
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  return (
    <UserForm
      initialData={data}
      onUpdate={handleUpdate}
      updateDisabled={
        !rights.updating || deleteUsers.isPending || deleteUsers.isSuccess
      }
      updateLoading={updateUser.isPending}
      onDelete={handleDelete}
      deleteDisabled={
        !rights.deleting ||
        deleteUsers.isSuccess ||
        data.roles?.some((role) => role.admin)
      }
      deleteLoading={deleteUsers.isPending}
    />
  );
};
