// apps/frontend/panel-react/src/features/roles/RoleUpdate.tsx
import { FC, useRef } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import {
  getErrorText,
  getUpdatedValues,
  IRole,
  TRoleUpdate,
} from "@workspace/shared";
import { RoleForm } from "@/entities/role/RoleForm";
import { ROUTES } from "@workspace/shared";
import { useDeleteRolesMutation, useUpdateRoleMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";

export const RoleUpdate: FC<{ data: IRole; onDelete?: () => void }> = ({
  data,
  onDelete,
}) => {
  const { t, i18n } = useTranslation();
  const updateRole = useUpdateRoleMutation();
  const deleteRoles = useDeleteRolesMutation();
  const cachedData = useRef(data);
  const rights = useRights(ROUTES.api.roles._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleUpdate = (fields: TRoleUpdate) => {
    const updatedValues = getUpdatedValues<TRoleUpdate>(
      cachedData.current,
      fields,
    );

    if (Object.keys(updatedValues).length === 0) {
      addAlert({ type: "warning", text: t("nothingToUpdate") });
      return;
    }

    updateRole.mutate(
      { id: data.id, fields: updatedValues },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          cachedData.current = { ...cachedData.current, ...updatedValues };
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  const handleDelete = () => {
    deleteRoles.mutate(
      { items: [data.id] },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          onDelete?.();
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  return (
    <RoleForm
      initialData={data}
      onUpdate={handleUpdate}
      updateDisabled={
        !rights.updating ||
        data.default ||
        deleteRoles.isPending ||
        deleteRoles.isSuccess
      }
      updateLoading={updateRole.isPending}
      onDelete={handleDelete}
      deleteDisabled={!rights.deleting || deleteRoles.isSuccess || data.default}
      deleteLoading={deleteRoles.isPending}
    />
  );
};

// apps/frontend/panel-vue/app/components/features/roles/RoleUpdate.vue
<script setup lang="ts">
import rolesApi from '~/components/entities/role/rolesApi'

const props = defineProps<{
  data: IRole
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.roles._)
const alertsStore = useAlertsStore()
const cachedData = ref<IRole>(props.data)
const updatedValues = ref<TRoleUpdate>({})
const {
  error: uError,
  execute: uExecute,
  status: uStatus,
} = rolesApi.update({
  id: props.data.id,
  fields: updatedValues,
})
const {
  error: dError,
  execute: dExecute,
  status: dStatus,
} = rolesApi.delete({ items: [props.data.id] })

function handleUpdate(fields: TRoleUpdate) {
  updatedValues.value = getUpdatedValues<TRoleUpdate>(
    cachedData.value,
    fields,
  )

  if (Object.keys(updatedValues.value).length > 0) {
    uExecute()
  }
  else {
    alertsStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(uStatus, () => {
  if (uStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    cachedData.value = { ...cachedData.value, ...updatedValues.value }
  }
})

watch(uError, () => {
  if (uError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(uError.value, locale.value),
    })
  }
})

watch(dStatus, () => {
  if (dStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(dError, () => {
  if (dError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(dError.value, locale.value),
    })
  }
})
</script>

<template>
  <RoleForm
    update-show
    delete-show
    :initial-data="data"
    :update-disabled="!rights.updating || data.default || dStatus === 'pending' || dStatus === 'success'"
    :update-loading="uStatus === 'pending'"
    :delete-disabled="!rights.deleting || dStatus === 'success' || data.default"
    :delete-loading="dStatus === 'pending'"
    @update="handleUpdate($event)"
    @delete="dExecute()"
  />
</template>
