// apps/frontend/panel-react/src/features/roles/RoleRightsUpdate.tsx
import { FC } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { getErrorText, IResource, IRole } from "@workspace/shared";
import { RoleRightsForm } from "@/entities/role/RoleRightsForm";
import { useUpdateRoleRightsMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const RoleRightsUpdate: FC<{
  role: IRole;
  resources: IResource[];
}> = ({ role, resources }) => {
  const { t, i18n } = useTranslation();
  const updateRoleRights = useUpdateRoleRightsMutation();
  const rights = useRights(ROUTES.api.roles._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  return (
    <RoleRightsForm
      role={role}
      resources={resources}
      onUpdate={(newRights) =>
        updateRoleRights.mutate(
          { id: role.id, fields: { items: newRights } },
          {
            onSuccess: () => addAlert({ type: "success", text: t("success") }),
            onError: (error) =>
              addAlert({
                type: "error",
                text: getErrorText(error, i18n.language),
              }),
          },
        )
      }
      updateDisabled={!rights.updating || role.default}
      updateLoading={updateRoleRights.isPending}
    />
  );
};

// apps/frontend/panel-vue/components/features/roles/RoleRightsUpdate.vue
<script setup lang="ts">
import rolesApi from '~/components/entities/role/rolesApi'

const { role, resources } = defineProps<{
  role: IRole
  resources: IResource[]
}>()

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.roles._)
const alertsStore = useAlertsStore()
const updatedRights = ref<IRights[]>(role.rights ?? [])
const { status, error, execute } = rolesApi.updateRights({
  id: role.id,
  fields: { items: updatedRights },
})

watch(error, () => {
  if (!error.value) {
    return
  }

  alertsStore.addAlert({
    type: 'error',
    text: getErrorText(error.value, locale.value),
  })
})

watch(status, () => {
  if (status.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
  }
})
</script>

<template>
  <RoleRightsForm
    :role="role"
    :resources="resources"
    :disabled="!rights.updating || role.default"
    :loading="status === 'pending'"
    @update="(newRights) => {
      updatedRights = newRights
      execute()
    }"
  />
</template>
