// apps/frontend/panel-vue/app/components/features/roles/RoleCreate.vue
<script setup lang="ts">
import rolesApi from '~/components/entities/role/rolesApi'

const emit = defineEmits<{
  create: [value: IRole]
}>()

const { t, locale } = useI18n()
const newData = ref<TRoleCreate>({
  name: '',
  description: '',
  enabled: false,
})
const { data, error, execute, status } = rolesApi.create(newData)
const alertsStore = useAlertsStore()
const rights = useRights(ROUTES.api.roles._)

watch(data, () => {
  if (data.value) {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('create', data.value)
  }
})

watch(error, () => {
  if (error.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
  }
})
</script>

<template>
  <RoleForm
    create-show
    :create-disabled="!rights.creating"
    :create-loading="status === 'pending' || Boolean(data)"
    @create="(fields) => {
      newData = fields
      execute()
    }"
  />
</template>

// apps/frontend/panel-react/src/features/roles/RoleCreate.tsx
import { FC } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { getErrorText, IRole, TRoleCreate } from "@workspace/shared";
import { RoleForm } from "@/entities/role/RoleForm";
import { useCreateRoleMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const RoleCreate: FC<{ onCreate?: (data: IRole) => void }> = ({
  onCreate,
}) => {
  const { t, i18n } = useTranslation();
  const createRole = useCreateRoleMutation();
  const rights = useRights(ROUTES.api.roles._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleCreate = (fields: TRoleCreate) => {
    createRole.mutate(fields, {
      onSuccess: (data) => {
        addAlert({ type: "success", text: t("success") });
        onCreate?.(data);
      },
      onError: (error) =>
        addAlert({
          type: "error",
          text: getErrorText(error, i18n.language),
        }),
    });
  };

  return (
    <RoleForm
      onCreate={handleCreate}
      createDisabled={!rights.creating}
      createLoading={createRole.isPending || Boolean(createRole.data)}
    />
  );
};
