// apps/frontend/panel-react/src/features/resources/ResourceCreate.tsx
import { FC } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { getErrorText, IResource, TResourceCreate } from "@workspace/shared";
import { ResourceForm } from "@/entities/resource/ResourceForm";
import { useCreateResourceMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const ResourceCreate: FC<{ onCreate?: (data: IResource) => void }> = ({
  onCreate,
}) => {
  const { t, i18n } = useTranslation();
  const createResource = useCreateResourceMutation();
  const rights = useRights(ROUTES.api.resources._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleCreate = (fields: TResourceCreate) => {
    createResource.mutate(fields, {
      onSuccess: (data) => {
        addAlert({ type: "success", text: t("success") });
        onCreate?.(data);
      },
      onError: (error) =>
        addAlert({
          type: "error",
          text: getErrorText(error, i18n.language),
        }),
    });
  };

  return (
    <ResourceForm
      onCreate={handleCreate}
      createDisabled={!rights.creating}
      createLoading={createResource.isPending || Boolean(createResource.data)}
    />
  );
};

// apps/frontend/panel-vue/components/features/resources/ResourceCreate.vue
<script setup lang="ts">
import resourcesApi from '~/components/entities/resource/resourcesApi'

const emit = defineEmits<{
  create: [value: IResource]
}>()

const { t, locale } = useI18n()
const newData = ref<TResourceCreate>({
  name: '',
  path: '',
  description: '',
  enabled: false,
})
const { data, error, execute, status } = resourcesApi.create(newData)
const alertsStore = useAlertsStore()
const rights = useRights(ROUTES.api.resources._)

watch(data, () => {
  if (data.value) {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('create', data.value)
  }
})

watch(error, () => {
  if (error.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
  }
})
</script>

<template>
  <ResourceForm
    create-show
    :create-disabled="!rights.creating"
    :create-loading="status === 'pending' || Boolean(data)"
    @create="(fields) => {
      newData = fields
      execute()
    }"
  />
</template>
