// apps/frontend/panel-vue/app/components/entities/user/UserForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

const props = defineProps<{
  initialData?: IUser
  createShow?: boolean
  createDisabled?: boolean
  createLoading?: boolean
  updateShow?: boolean
  updateDisabled?: boolean
  updateLoading?: boolean
  deleteShow?: boolean
  deleteDisabled?: boolean
  deleteLoading?: boolean
}>()
const emit = defineEmits<{
  create: [value: TUserCreate]
  update: [value: TUserUpdate]
  delete: []
}>()

const data = reactive<IUser>(props.initialData ?? {
  id: '',
  email: '',
  password: '',
  name: '',
  verified: false,
  enabled: false,
})
const { t } = useI18n()
const emailIsValid = (value: string) =>
  testString(EMAIL_REGEX, value) || t('emailValidationI18N')
const nameIsValid = (value: string) =>
  testString(NAME_REGEX, value) || t('nameValidation')
const passwordIsValid = (value: string) =>
  testString(PASSWORD_REGEX, value) || t('passwordValidation')

async function handleSubmit(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  if (props.createShow && data.email && data.password) {
    emit('create', {
      email: data.email,
      password: data.password,
      name: data.name,
      enabled: data.enabled,
    })
  }

  if (props.updateShow) {
    emit('update', {
      name: data.name,
      enabled: data.enabled,
    })
  }
}
</script>

<template>
  <FormBase @submit="handleSubmit">
    <FormField
      v-if="createShow"
      :hint="$t('emailValidationI18N')"
      :label="$t('email')"
      :model-value="data.email ?? ''"
      name="email"
      required
      :rules="[emailIsValid]"
      type="email"
      @update:model-value="data.email = $event ?? ''"
    />
    <FormField
      :label="$t('name')"
      :model-value="data.name"
      name="name"
      required
      :rules="[nameIsValid]"
      @update:model-value="data.name = $event ?? ''"
    />
    <FormPassword
      v-if="createShow"
      :hint="$t('passwordValidation')"
      :label="$t('password')"
      :model-value="data.password ?? ''"
      name="password"
      required
      :rules="[passwordIsValid]"
      @update:model-value="data.password = $event ?? ''"
    />
    <FormCheckbox
      :label="$t('enabled')"
      :model-value="data.enabled"
      :disabled="initialData?.roles?.some((role) => role.admin)"
      name="enabled"
      @update:model-value="data.enabled = Boolean($event)"
    />
    <FormButton
      v-if="createShow"
      :disabled="createDisabled"
      :loading="createLoading"
      color="info"
      prepand-icon="mdi-plus"
      type="submit"
    >
      {{ $t('create') }}
    </FormButton>
    <FormButton
      v-if="updateShow"
      :disabled="updateDisabled"
      :loading="updateLoading"
      color="success"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
    <FormButton
      v-if="deleteShow"
      :disabled="deleteDisabled"
      :loading="deleteLoading"
      color="error"
      prepand-icon="mdi-delete"
      type="button"
      @click="emit('delete')"
    >
      {{ $t('delete') }}
    </FormButton>
  </FormBase>
</template>

// apps/frontend/panel-react/src/entities/user/UserForm.tsx
import { FC, SubmitEventHandler, useMemo, useState } from "react";
import AddIcon from "@mui/icons-material/Add";
import SaveIcon from "@mui/icons-material/Save";
import DeleteIcon from "@mui/icons-material/Delete";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { FormField } from "@/shared/ui/form/FormField";
import { FormButton } from "@/shared/ui/form/FormButton";
import { FormCheckbox } from "@/shared/ui/form/FormCheckbox";
import {
  EMAIL_REGEX,
  NAME_REGEX,
  PASSWORD_REGEX,
  testString,
  IUser,
  TUserCreate,
  TUserUpdate,
} from "@workspace/shared";
import { FormPassword } from "@/shared/ui/form/FormPassword";
import { IEntityForm } from "@/shared/lib/types";

export const UserForm: FC<IEntityForm<IUser, TUserCreate, TUserUpdate>> = ({
  initialData,
  onCreate,
  createDisabled,
  createLoading,
  onUpdate,
  updateDisabled,
  updateLoading,
  onDelete,
  deleteDisabled,
  deleteLoading,
}) => {
  const { t } = useTranslation();
  const [data, setData] = useState<IUser>(
    () =>
      initialData ?? {
        id: "",
        email: "",
        password: "",
        name: "",
        enabled: false,
        verified: false,
      },
  );
  const emailIsValid = useMemo(
    () => testString(EMAIL_REGEX, data.email ?? ""),
    [data],
  );
  const nameIsValid = useMemo(() => testString(NAME_REGEX, data.name), [data]);
  const passwordIsValid = useMemo(
    () => testString(PASSWORD_REGEX, data.password ?? ""),
    [data],
  );

  const handleSubmit: SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();

    if (data.email && data.password) {
      onCreate?.({
        email: data.email,
        password: data.password,
        name: data.name,
        enabled: data.enabled,
      });
    }

    onUpdate?.({
      name: data.name,
      enabled: data.enabled,
    });
  };

  return (
    <FormBase onSubmit={handleSubmit}>
      {onCreate && (
        <FormField
          required
          name="email"
          type="email"
          label={t("email")}
          value={data.email ?? ""}
          onChange={(event) => setData({ ...data, email: event.target.value })}
          helperText={t("emailValidation")}
          color={emailIsValid ? "success" : "error"}
          error={!emailIsValid && (data.email ?? "").length > 0}
        />
      )}
      <FormField
        required
        name="name"
        label={t("name")}
        value={data.name}
        onChange={(event) => setData({ ...data, name: event.target.value })}
        helperText={t("nameValidation")}
        color={nameIsValid ? "success" : "error"}
        error={!nameIsValid && data.name.length > 0}
      />
      {onCreate && (
        <FormPassword
          required
          autoComplete="new-password"
          name="password"
          label={t("password")}
          value={data.password ?? ""}
          onChange={(event) =>
            setData({ ...data, password: event.target.value })
          }
          helperText={t("passwordValidation")}
          color={passwordIsValid ? "success" : "error"}
          error={!passwordIsValid && (data.password ?? "").length > 0}
        />
      )}
      <FormCheckbox
        labelProps={{ label: t("enabled") }}
        name="enabled"
        value="enabled"
        checked={data.enabled}
        onChange={() => setData({ ...data, enabled: !data.enabled })}
        disabled={initialData?.roles?.some((role) => role.admin)}
      />
      {onCreate && (
        <FormButton
          type="submit"
          color="primary"
          startIcon={<AddIcon />}
          disabled={createDisabled}
          loading={createLoading}
        >
          {t("create")}
        </FormButton>
      )}
      {onUpdate && (
        <FormButton
          type="submit"
          color="success"
          startIcon={<SaveIcon />}
          disabled={updateDisabled}
          loading={updateLoading}
        >
          {t("update")}
        </FormButton>
      )}
      {onDelete && (
        <FormButton
          color="error"
          startIcon={<DeleteIcon />}
          onClick={onDelete}
          disabled={deleteDisabled}
          loading={deleteLoading}
        >
          {t("delete")}
        </FormButton>
      )}
    </FormBase>
  );
};
