// apps/frontend/panel-react/src/features/profile/ChangeEmailConfirmForm.tsx
import { FC, SubmitEventHandler, useState } from "react";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { FormButton } from "@/shared/ui/form/FormButton";
import { FormField } from "@/shared/ui/form/FormField";
import { useRights } from "@/shared/hooks/useRights";
import { getErrorText } from "@workspace/shared";
import { ROUTES } from "@workspace/shared";
import { useChangeEmailConfirmMutation } from "./mutations";
import { useProfileStore } from "@/entities/profile/store";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { FetchError } from "@/shared/api/FetchError";

export const ChangeEmailConfirmForm: FC<{
  email: string;
  onClose?: () => void;
}> = ({ email, onClose }) => {
  const profile = useProfileStore((s) => s.profile);
  const setProfile = useProfileStore((s) => s.setProfile);
  const addAlert = useAlertsStore((s) => s.addAlert);
  const { t, i18n } = useTranslation();
  const changeEmailConfirm = useChangeEmailConfirmMutation();
  const rights = useRights(ROUTES.api.profile._);
  const [code, setCode] = useState("");

  const handleSubmit: SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();

    changeEmailConfirm.mutate(
      { code },
      {
        onSuccess: () => {
          if (profile) {
            setProfile({ ...profile, email });
          }

          addAlert({ type: "success", text: t("success") });
          onClose?.();
        },
        onError: (error) => {
          if (error instanceof FetchError && error.status === 404) {
            addAlert({ type: "error", text: t("wrongEmailOrCode") });
          } else {
            addAlert({
              type: "error",
              text: getErrorText(error, i18n.language),
            });
          }
        },
      },
    );
  };

  return (
    <FormBase onSubmit={handleSubmit}>
      <FormField
        required
        autoComplete="off"
        name="code"
        label={t("code")}
        value={code}
        onChange={(event) => setCode(event.target.value)}
        helperText={`${t("codeFromEmail")} (${email})`}
      />
      <FormButton
        type="submit"
        fullWidth
        disabled={!rights.updating}
        loading={changeEmailConfirm.isPending || changeEmailConfirm.isSuccess}
      >
        {t("confirm")}
      </FormButton>
      <FormButton fullWidth color="error" onClick={onClose}>
        {t("close")}
      </FormButton>
    </FormBase>
  );
};

// apps/frontend/panel-vue/components/features/profile/ChangeEmailConfirmForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

import profileApi from '~/components/entities/profile/profileApi'

const props = defineProps<{
  email: string
}>()
const emit = defineEmits<{
  close: []
}>()

const { t, locale } = useI18n()
const alertsStore = useAlertsStore()
const profileStore = useProfileStore()
const code = ref('')
const codeIsValid = (value: string) =>
  value.length > 0 || `${t('codeFromEmail')} (${props.email})`
const { status, error, execute } = profileApi.changeEmailConfirm({ code })
const rights = useRights(ROUTES.api.profile._)

async function submitHandler(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  execute()
}

watch(error, () => {
  if (!error.value) {
    return
  }

  switch (error.value.statusCode) {
    case 404:
      alertsStore.addAlert({ type: 'error', text: t('wrongEmailOrCode') })
      break
    default:
      alertsStore.addAlert({
        type: 'error',
        text: getErrorText(error.value, locale.value),
      })
  }
})

watch(status, () => {
  if (status.value === 'success') {
    if (profileStore.profile) {
      profileStore.setProfile({ ...profileStore.profile, email: props.email })
    }

    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('close')
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <FormField
      v-model="code"
      :hint="`${$t('codeFromEmail')} (${email})`"
      :label="$t('code')"
      name="code"
      required
      :rules="[codeIsValid]"
    />
    <FormButton
      block
      color="success"
      :disabled="!rights.updating"
      :loading="status === 'pending' || status === 'success'"
      type="submit"
    >
      {{ $t('confirm') }}
    </FormButton>
    <FormButton
      block
      color="error"
      type="button"
      @click="$emit('close')"
    >
      {{ $t('close') }}
    </FormButton>
  </FormBase>
</template>
