// apps/frontend/panel-react/src/features/profile/SessionForm.tsx
import { FC, SubmitEventHandler, useState } from "react";
import { UAParser } from "ua-parser-js";
import DeleteIcon from "@mui/icons-material/Delete";
import ComputerIcon from "@mui/icons-material/Computer";
import SmartphoneIcon from "@mui/icons-material/Smartphone";
import {
  Card,
  CardActions,
  CardContent,
  Chip,
  IconButton,
  styled,
  Typography,
} from "@mui/material";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { theme } from "@/shared/ui/theme";
import { useRights } from "@/shared/hooks/useRights";
import {
  getDateString,
  getErrorText,
  TSessionExternal,
} from "@workspace/shared";
import { ROUTES } from "@workspace/shared";
import { useDeleteSessionsMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";

export const SessionForm: FC<{
  session: TSessionExternal;
  onDelete?: () => void;
}> = ({ session, onDelete }) => {
  const { t, i18n } = useTranslation();
  const rights = useRights(ROUTES.api.profile._);
  const [userAgent] = useState(() =>
    new UAParser(session.userAgent).getResult(),
  );
  const deleteSessions = useDeleteSessionsMutation();
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleSubmit: SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    deleteSessions.mutate(
      { items: [session.id] },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          onDelete?.();
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  return (
    <FormBase onSubmit={handleSubmit}>
      <Session>
        <SessionContent>
          {userAgent.device.vendor ? (
            <>
              <SmartphoneIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.device.vendor} {userAgent.device.model}
                {","}&nbsp;
              </Typography>
            </>
          ) : (
            <>
              <ComputerIcon sx={{ mr: 1 }} />
              <Typography component="span" variant="body2">
                {userAgent.os.name} {userAgent.os.version}
                {","}&nbsp;
              </Typography>
            </>
          )}
          <Typography component="span" variant="body2">
            {userAgent.browser.name} {userAgent.browser.version}
            {","}&nbsp;
          </Typography>
          <Typography component="span" variant="body2" sx={{ opacity: 0.8 }}>
            {session.ip}
            {","}&nbsp;
          </Typography>
          <Typography
            component="span"
            variant="body2"
            sx={{ mr: 1, opacity: 0.6 }}
          >
            {getDateString(session.updatedAt)}
          </Typography>
          {session.current && (
            <Chip
              label={t("current")}
              color="success"
              variant="outlined"
              size="small"
            />
          )}
        </SessionContent>
        <CardActions sx={{ pr: 2 }}>
          <IconButton
            edge="end"
            color="error"
            aria-label="sign out"
            title={t("signOut")}
            disabled={
              !rights.updating ||
              deleteSessions.isPending ||
              deleteSessions.isSuccess ||
              session.current
            }
            type="submit"
          >
            <DeleteIcon />
          </IconButton>
        </CardActions>
      </Session>
    </FormBase>
  );
};

const Session = styled(Card)`
  display: flex;
  flex-direction: row;
  margin-bottom: ${theme.spacing(1)};
`;

const SessionContent = styled(CardContent)`
  flex-grow: 1;
  display: flex;
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
`;

// apps/frontend/panel-vue/components/features/profile/SessionForm.vue
<script setup lang="ts">
import { UAParser } from 'ua-parser-js'

import authApi from '~/components/entities/auth/authApi'
import profileApi from '~/components/entities/profile/profileApi'

const props = defineProps<{
  session: TSessionExternal
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const router = useRouter()
const rights = useRights(ROUTES.api.profile._)
const mainStore = useMainStore()
const userAgent = new UAParser(props.session.userAgent).getResult()
const updatedAt = getDateString(props.session.updatedAt)
const { status: dsStatus, error: dsError, execute: dsExecute } = profileApi.deleteSessions({ items: [props.session.id] })
const { status: soStatus, error: soError, execute: soExecute } = authApi.signOut()

async function submitHandler() {
  if (props.session.current) {
    soExecute()
  }
  else {
    dsExecute()
  }
}

watch(dsError, () => {
  if (!dsError.value) {
    return
  }

  mainStore.addAlert({
    type: 'error',
    text: getErrorText(dsError.value, locale.value),
  })
})

watch(dsStatus, () => {
  if (dsStatus.value === 'success') {
    mainStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(soError, () => {
  if (!soError.value) {
    return
  }

  if (soError.value.statusCode === 401) {
    router.push(ROUTES.ui.signIn)
  }
  else {
    mainStore.addAlert({
      type: 'error',
      text: getErrorText(soError.value, locale.value),
    })
  }
})

watch(soStatus, () => {
  if (soStatus.value === 'success') {
    router.push(ROUTES.ui.signIn)
  }
})
</script>

<template>
  <FormBase @submit="submitHandler">
    <v-card class="mb-1 d-flex flex-row">
      <v-card-text class="d-flex flex-row align-center">
        <template v-if="userAgent.device.vendor">
          <v-icon
            class="mr-1"
            icon="mdi-cellphone"
          />
          <span class="text-body-2">
            {{ userAgent.device.vendor }}{{ ' ' }} {{ userAgent.device.model
            }}{{ ',' }}&nbsp;
          </span>
        </template>
        <template v-else>
          <v-icon
            class="mr-1"
            icon="mdi-laptop"
          />
          <span class="text-body-2">
            {{ userAgent.os.name }} {{ userAgent.os.version }}{{ ',' }}&nbsp;
          </span>
        </template>
        <span class="text-body-2">
          {{ userAgent.browser.name }} {{ userAgent.browser.version
          }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-80">
          {{ session.ip }}{{ ',' }}&nbsp;
        </span>
        <span class="text-body-2 opacity-60 mr-2">
          {{ updatedAt }}
        </span>
        <v-chip
          v-if="session.current"
          color="success"
          variant="outlined"
        >
          {{
            $t('current')
          }}
        </v-chip>
      </v-card-text>
      <v-card-actions>
        <v-btn
          color="error"
          :disabled="!rights.updating || dsStatus === 'pending' || dsStatus === 'success'"
          icon="mdi-delete"
          type="submit"
          variant="text"
        />
      </v-card-actions>
    </v-card>
  </FormBase>
</template>
