// apps/frontend/panel-react/src/entities/role/RoleForm.tsx
import { FC, SubmitEventHandler, useState } from "react";
import AddIcon from "@mui/icons-material/Add";
import SaveIcon from "@mui/icons-material/Save";
import DeleteIcon from "@mui/icons-material/Delete";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { FormField } from "@/shared/ui/form/FormField";
import { FormButton } from "@/shared/ui/form/FormButton";
import { FormCheckbox } from "@/shared/ui/form/FormCheckbox";
import { IRole, TRoleCreate, TRoleUpdate } from "@workspace/shared";
import { IEntityForm } from "@/shared/lib/types";

export const RoleForm: FC<IEntityForm<IRole, TRoleCreate, TRoleUpdate>> = ({
  initialData,
  onCreate,
  createDisabled,
  createLoading,
  onUpdate,
  updateDisabled,
  updateLoading,
  onDelete,
  deleteDisabled,
  deleteLoading,
}) => {
  const { t } = useTranslation();
  const [data, setData] = useState<IRole>(
    () =>
      initialData ?? {
        id: "",
        name: "",
        description: "",
        default: false,
        enabled: false,
        admin: false,
      },
  );

  const handleSubmit: SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    onCreate?.({
      name: data.name,
      description: data.description,
      enabled: data.enabled,
    });
    onUpdate?.({
      name: data.name,
      description: data.description,
      enabled: data.enabled,
    });
  };

  return (
    <FormBase onSubmit={handleSubmit}>
      <FormField
        required
        name="name"
        label={t("name")}
        value={data.name}
        onChange={(event) => setData({ ...data, name: event.target.value })}
      />
      <FormField
        name="description"
        label={t("description")}
        value={data.description ?? ""}
        onChange={(event) =>
          setData({ ...data, description: event.target.value })
        }
      />
      <FormCheckbox
        labelProps={{ label: t("enabled") }}
        name="enabled"
        value="enabled"
        checked={data.enabled}
        onChange={() => setData({ ...data, enabled: !data.enabled })}
      />
      {onCreate && (
        <FormButton
          type="submit"
          color="primary"
          startIcon={<AddIcon />}
          disabled={createDisabled}
          loading={createLoading}
        >
          {t("create")}
        </FormButton>
      )}
      {onUpdate && (
        <FormButton
          type="submit"
          color="success"
          startIcon={<SaveIcon />}
          disabled={updateDisabled}
          loading={updateLoading}
        >
          {t("update")}
        </FormButton>
      )}
      {onDelete && (
        <FormButton
          color="error"
          startIcon={<DeleteIcon />}
          onClick={onDelete}
          disabled={deleteDisabled}
          loading={deleteLoading}
        >
          {t("delete")}
        </FormButton>
      )}
    </FormBase>
  );
};

// apps/frontend/panel-vue/app/components/entities/role/RoleForm.vue
<script setup lang="ts">
import type { SubmitEventPromise } from 'vuetify'

const props = defineProps<{
  initialData?: IRole
  createShow?: boolean
  createDisabled?: boolean
  createLoading?: boolean
  updateShow?: boolean
  updateDisabled?: boolean
  updateLoading?: boolean
  deleteShow?: boolean
  deleteDisabled?: boolean
  deleteLoading?: boolean
}>()
const emit = defineEmits<{
  create: [value: TRoleCreate]
  update: [value: TRoleUpdate]
  delete: []
}>()

const data = reactive<IRole>(props.initialData ?? {
  id: '',
  name: '',
  description: '',
  default: false,
  enabled: false,
  admin: false,
})
const nameIsValid = (value: string) => value.length > 0

async function handleSubmit(event: SubmitEventPromise) {
  const results = await event

  if (!results.valid) {
    return
  }

  if (props.createShow) {
    emit('create', {
      name: data.name,
      description: data.description,
      enabled: data.enabled,
    })
  }

  if (props.updateShow) {
    emit('update', {
      name: data.name,
      description: data.description,
      enabled: data.enabled,
    })
  }
}
</script>

<template>
  <FormBase @submit="handleSubmit">
    <FormField
      :label="$t('name')"
      :model-value="data.name"
      name="name"
      required
      :rules="[nameIsValid]"
      @update:model-value="data.name = $event ?? ''"
    />
    <FormField
      :label="$t('description')"
      :model-value="data.description ?? ''"
      name="description"
      @update:model-value="data.description = $event"
    />
    <FormCheckbox
      :label="$t('enabled')"
      :model-value="data.enabled"
      name="enabled"
      @update:model-value="data.enabled = Boolean($event)"
    />
    <FormButton
      v-if="createShow"
      color="info"
      :disabled="createDisabled"
      :loading="createLoading"
      prepand-icon="mdi-plus"
      type="submit"
    >
      {{ $t('create') }}
    </FormButton>
    <FormButton
      v-if="updateShow"
      :disabled="updateDisabled"
      :loading="updateLoading"
      color="success"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
    <FormButton
      v-if="deleteShow"
      :disabled="deleteDisabled"
      :loading="deleteLoading"
      color="error"
      prepand-icon="mdi-delete"
      type="button"
      @click="emit('delete')"
    >
      {{ $t('delete') }}
    </FormButton>
  </FormBase>
</template>
