// apps/frontend/panel-react/src/widgets/sidebar/SidebarMenuItem.tsx
import { FC, MouseEventHandler, ReactNode, useMemo, useState } from "react";
import ListItem from "@mui/material/ListItem";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Divider from "@mui/material/Divider";
import Collapse from "@mui/material/Collapse";
import ExpandMore from "@mui/icons-material/ExpandMore";
import ExpandLess from "@mui/icons-material/ExpandLess";
import { usePathname, useRouter } from "next/navigation";

import { checkActiveLink, IMenuItem } from "@workspace/shared";

export const SidebarMenuItem: FC<IMenuItem<ReactNode>> = ({
  href,
  title,
  icon,
  childs,
}) => {
  const router = useRouter();
  const pathname = usePathname();
  const [open, setOpen] = useState(() =>
    checkActiveLink(pathname, { href, childs }),
  );

  const handleLink: MouseEventHandler<HTMLDivElement> = (event) => {
    event.preventDefault();

    if (href) {
      router.push(href);
    }

    if (childs) {
      setOpen(!open);
    }
  };

  const selected = useMemo(() => {
    let result = Boolean(href);
    const pathArr = pathname.split("/");
    const linkArr = href?.split("/") || [];

    linkArr.forEach((value, index) => {
      if (value != pathArr[index]) {
        result = false;
      }
    });

    return result;
  }, [pathname, href]);

  return (
    <>
      <ListItem disablePadding>
        <ListItemButton
          {...(href && { href })}
          selected={selected}
          onClick={handleLink}
        >
          {icon && <ListItemIcon>{icon}</ListItemIcon>}
          <ListItemText primary={title} />
          {childs && (open ? <ExpandLess /> : <ExpandMore />)}
        </ListItemButton>
      </ListItem>
      {childs && (
        <Collapse in={open} timeout="auto">
          <Divider />
          {childs.map((item, index) => (
            <SidebarMenuItem
              key={`sbmi:${index}:${item.title}:${item.href}`}
              {...item}
            />
          ))}
        </Collapse>
      )}
    </>
  );
};

// apps/frontend/panel-vue/app/components/widgets/sidebar/SidebarMenuItem.vue
<script setup lang="ts">
const props = defineProps<{
  title?: string
  href?: string
  icon?: string
  childs?: IMenuItem<string>[]
}>()

const route = useRoute()
const router = useRouter()
const selected = ref(false)

watch(
  () => route.path,
  () => {
    let result = Boolean(props.href)
    const pathArr = route.path.split('/')
    const linkArr = props.href?.split('/') || []
    linkArr.forEach((value, index) => {
      if (value !== pathArr[index]) {
        result = false
      }
    })
    selected.value = result
  },
  { immediate: true },
)
</script>

<template>
  <v-list-group
    v-if="childs?.length"
    :fluid="true"
    :value="`${title}: ${href}`"
  >
    <template #activator="{ props: itemProps }">
      <v-list-item
        v-bind="itemProps"
        :prepend-icon="icon"
        :title="title"
      />
    </template>
    <v-divider />
    <SidebarMenuItem
      v-for="child of childs"
      :key="`sbmi:${child.title}:${child.href}`"
      v-bind="child"
    />
  </v-list-group>
  <v-list-item
    v-else
    :active="selected"
    :href="href"
    link
    :prepend-icon="icon"
    :title="title"
    @click.prevent="router.push(href || '#')"
  />
</template>
