// apps/frontend/panel-vue/app/components/features/auth/SignInGoogleForm.vue
<script setup lang="ts">
import authApi from '~/components/entities/auth/authApi'

const { t, locale } = useI18n()
const errorText = ref<string | null>(null)
const hash = new URLSearchParams(location?.hash.slice(1) || '')
const { data, error, execute } = authApi.signInGoogle({ googleAccessToken: hash.get('access_token')! })

const handleMessage = (event: MessageEvent<IWindowMessage<string>>) => {
  if (event.data.type !== ROUTES.ui.signInGoogle || !data.value) {
    return
  }

  if (event.data.payload === hash.get('state')) {
    const message: IWindowMessage<IUser> = {
      type: ROUTES.ui.signInGoogle,
      payload: toRaw(data.value),
    }

    event.source?.postMessage(message)
    window.removeEventListener('message', handleMessage)
  }

  window.close()
}

onMounted(() => {
  if (hash.has('access_token')) {
    execute()
  }
  else {
    errorText.value = t('error')
  }

  window.addEventListener('message', handleMessage)
})

watch(error, () => {
  switch (error.value?.statusCode) {
    case 410:
      errorText.value = t('userDeleted')
      break
    default:
      errorText.value = getErrorText(error.value, locale.value)
  }
})

onUnmounted(() => {
  window.removeEventListener('message', handleMessage)
})
</script>

<template>
  <FormBase>
    <FormAlert
      v-if="errorText"
      :text="errorText"
      type="error"
    />
    <v-card-text
      v-else
      class="text-center py-3"
    >
      {{ $t('loading') }}...
    </v-card-text>
  </formbase>
</template>

// apps/frontend/panel-react/src/features/auth/SignInGoogleForm.tsx
import { FC, useCallback, useEffect, useMemo, useState } from "react";
import { Typography } from "@mui/material";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { FormAlert } from "@/shared/ui/form/FormAlert";
import { IUser, IWindowMessage, getErrorText } from "@workspace/shared";
import { ROUTES } from "@workspace/shared";
import { useSignInGoogleMutation } from "./mutations";
import { FetchError } from "@/shared/api/FetchError";

export const SignInGoogleForm: FC = () => {
  const { t, i18n } = useTranslation();
  const { mutate, error, data } = useSignInGoogleMutation();
  const [hash] = useState(() => new URLSearchParams(location.hash.slice(1)));

  const errorText = useMemo(() => {
    if (!hash.has("access_token")) {
      return t("error");
    }

    if (error instanceof FetchError) {
      switch (error.status) {
        case 410:
          return t("userDeleted");
        default:
          return getErrorText(error, i18n.language);
      }
    }

    return null;
  }, [t, i18n, error, hash]);

  const handleMessage = useCallback(
    (event: MessageEvent<IWindowMessage<string>>) => {
      if (event.data.type !== ROUTES.ui.signInGoogle || !data) {
        return;
      }

      if (event.data.payload === hash.get("state")) {
        const message: IWindowMessage<IUser> = {
          type: ROUTES.ui.signInGoogle,
          payload: data,
        };
        event.source?.postMessage(message);
      }

      window.close();
    },
    [data, hash],
  );

  useEffect(() => {
    window.addEventListener("message", handleMessage);

    return () => {
      window.removeEventListener("message", handleMessage);
    };
  }, [handleMessage]);

  useEffect(() => {
    if (hash.has("access_token")) {
      mutate({ googleAccessToken: hash.get("access_token")! });
    }
  }, [mutate, hash]);

  return (
    <FormBase>
      {errorText ? (
        <FormAlert severity="error">{errorText}</FormAlert>
      ) : (
        <Typography
          align="center"
          variant="subtitle1"
          sx={{ mt: 2, opacity: 0.75 }}
        >
          {t("loading")}...
        </Typography>
      )}
    </FormBase>
  );
};
