// apps/frontend/panel-react/src/entities/user/UserRolesForm.tsx
import { FC, SubmitEventHandler, useState } from "react";
import SaveIcon from "@mui/icons-material/Save";
import { useTranslation } from "react-i18next";

import { FormBase } from "@/shared/ui/form/FormBase";
import { FormButton } from "@/shared/ui/form/FormButton";
import { FormCheckbox } from "@/shared/ui/form/FormCheckbox";
import { IRole, IUser, IUsersRoles } from "@workspace/shared";
import { IEntityFormUpdate } from "@/shared/lib/types";

export const UserRolesForm: FC<
  IEntityFormUpdate<IUsersRoles[]> & {
    user: IUser;
    roles: IRole[];
  }
> = ({ user, roles, onUpdate, updateDisabled, updateLoading }) => {
  const { t } = useTranslation();
  const [updatedRoles, setUpdatedRoles] = useState<IUsersRoles[]>(
    () =>
      user.roles?.map((value) => ({
        roleId: value.id,
        userId: user.id,
      })) ?? [],
  );

  const handleSubmit: SubmitEventHandler<HTMLFormElement> = (event) => {
    event.preventDefault();
    onUpdate?.(updatedRoles);
  };

  const updateRoles = (newRole: IUsersRoles) => {
    let find = false;

    const filtered = updatedRoles.filter((value) => {
      if (newRole.userId === value.userId && newRole.roleId === value.roleId) {
        find = true;
        return false;
      } else {
        return true;
      }
    });

    if (!find) {
      filtered.push(newRole);
    }

    setUpdatedRoles(filtered);
  };

  return (
    <FormBase onSubmit={handleSubmit}>
      {roles.map((role) => (
        <FormCheckbox
          key={role.id}
          labelProps={{ label: role.name, sx: { display: "inline-flex" } }}
          name="role[]"
          value="allowed"
          checked={updatedRoles.some((value) => value.roleId === role.id)}
          onChange={() => updateRoles({ roleId: role.id, userId: user.id })}
          disabled={role.admin}
        />
      ))}
      <br />
      <FormButton
        type="submit"
        color="success"
        startIcon={<SaveIcon />}
        disabled={updateDisabled}
        loading={updateLoading}
      >
        {t("update")}
      </FormButton>
    </FormBase>
  );
};

// apps/frontend/panel-vue/app/components/entities/user/UserRolesForm.vue
<script setup lang="ts">
const { user } = defineProps<{
  user: IUser
  roles: IRole[]
  disabled?: boolean
  loading?: boolean
}>()
const emit = defineEmits<{
  update: [value: IUsersRoles[]]
}>()

const updatedRoles = ref<IUsersRoles[]>(
  user.roles?.map(role => ({ roleId: role.id, userId: user.id })) ?? [],
)

function handleSubmit() {
  emit('update', updatedRoles.value)
}

function setRoles(newRole: IUsersRoles) {
  let find = false

  const filtered = updatedRoles.value.filter((value) => {
    if (newRole.userId === value.userId && newRole.roleId === value.roleId) {
      find = true
      return false
    }
    else {
      return true
    }
  })

  if (!find) {
    filtered.push(newRole)
  }

  updatedRoles.value = filtered
}
</script>

<template>
  <FormBase @submit="handleSubmit">
    <div class="d-flex flex-row">
      <span
        v-for="role of roles"
        :key="role.id"
        class="mr-6"
      >
        <FormCheckbox
          :label="role.name"
          :model-value="updatedRoles.some((value) => value.roleId === role.id)"
          :name="`${role.name}.${role.id}`"
          :disabled="role.admin"
          @update:model-value="setRoles({ roleId: role.id, userId: user.id })"
        />
      </span>
    </div>
    <FormButton
      color="success"
      :disabled="disabled"
      :loading="loading"
      prepand-icon="mdi-content-save"
      type="submit"
    >
      {{ $t('update') }}
    </FormButton>
  </FormBase>
</template>
