// apps/frontend/panel-react/src/features/resources/ResourceUpdate.tsx
import { FC, useRef } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import {
  IResource,
  TResourceUpdate,
  getErrorText,
  getUpdatedValues,
} from "@workspace/shared";
import { ResourceForm } from "@/entities/resource/ResourceForm";
import { ROUTES } from "@workspace/shared";
import {
  useDeleteResourcesMutation,
  useUpdateResourceMutation,
} from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";

export const ResourceUpdate: FC<{ data: IResource; onDelete?: () => void }> = ({
  data,
  onDelete,
}) => {
  const { t, i18n } = useTranslation();
  const updateResource = useUpdateResourceMutation();
  const deleteResources = useDeleteResourcesMutation();
  const cachedData = useRef(data);
  const rights = useRights(ROUTES.api.resources._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleUpdate = (fields: TResourceUpdate) => {
    const updatedValues = getUpdatedValues<TResourceUpdate>(
      cachedData.current,
      fields,
    );

    if (Object.keys(updatedValues).length === 0) {
      addAlert({ type: "warning", text: t("nothingToUpdate") });
      return;
    }

    updateResource.mutate(
      { id: data.id, fields: updatedValues },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          cachedData.current = { ...cachedData.current, ...updatedValues };
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  const handleDelete = () => {
    deleteResources.mutate(
      { items: [data.id] },
      {
        onSuccess: () => {
          addAlert({ type: "success", text: t("success") });
          onDelete?.();
        },
        onError: (error) =>
          addAlert({ type: "error", text: getErrorText(error, i18n.language) }),
      },
    );
  };

  return (
    <ResourceForm
      initialData={data}
      onUpdate={handleUpdate}
      updateDisabled={
        !rights.updating ||
        data.default ||
        deleteResources.isPending ||
        deleteResources.isSuccess
      }
      updateLoading={updateResource.isPending}
      onDelete={handleDelete}
      deleteDisabled={
        !rights.deleting || deleteResources.isSuccess || data.default
      }
      deleteLoading={deleteResources.isPending}
    />
  );
};

// apps/frontend/panel-vue/app/components/features/resources/ResourceUpdate.vue
<script setup lang="ts">
import resourcesApi from '~/components/entities/resource/resourcesApi'

const props = defineProps<{
  data: IResource
}>()
const emit = defineEmits<{
  delete: []
}>()

const { t, locale } = useI18n()
const rights = useRights(ROUTES.api.resources._)
const alertsStore = useAlertsStore()
const cachedData = ref<IResource>(props.data)
const updatedValues = ref<TResourceUpdate>({})
const {
  error: uError,
  execute: uExecute,
  status: uStatus,
} = resourcesApi.update({
  id: props.data.id,
  fields: updatedValues,
})
const {
  error: dError,
  execute: dExecute,
  status: dStatus,
} = resourcesApi.delete({ items: [props.data.id] })

function handleUpdate(fields: TResourceUpdate) {
  updatedValues.value = getUpdatedValues<TResourceUpdate>(
    cachedData.value,
    fields,
  )

  if (Object.keys(updatedValues.value).length > 0) {
    uExecute()
  }
  else {
    alertsStore.addAlert({ type: 'warning', text: t('nothingToUpdate') })
  }
}

watch(uStatus, () => {
  if (uStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    cachedData.value = { ...cachedData.value, ...updatedValues.value }
  }
})

watch(uError, () => {
  if (uError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(uError.value, locale.value),
    })
  }
})

watch(dStatus, () => {
  if (dStatus.value === 'success') {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('delete')
  }
})

watch(dError, () => {
  if (dError.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(dError.value, locale.value),
    })
  }
})
</script>

<template>
  <ResourceForm
    update-show
    delete-show
    :initial-data="data"
    :update-disabled="!rights.updating || data.default || dStatus === 'pending' || dStatus === 'success'"
    :update-loading="uStatus === 'pending'"
    :delete-disabled="!rights.deleting || dStatus === 'success' || data.default"
    :delete-loading="dStatus === 'pending'"
    @update="handleUpdate($event)"
    @delete="dExecute()"
  />
</template>
