// apps/frontend/panel-react/src/entities/resource/ResourceRights.tsx
import { FC, useMemo } from "react";
import {
  FormControl,
  FormGroup,
  FormHelperText,
  FormLabel,
} from "@mui/material";
import { useTranslation } from "react-i18next";

import { FormCheckbox } from "@/shared/ui/form/FormCheckbox";
import { IResource, IRights } from "@workspace/shared";

export const ResourceRights: FC<{
  roleId: string;
  resource: IResource;
  rights?: IRights;
  onUpdate: (newRights: IRights) => void;
}> = ({ roleId, resource, rights, onUpdate }) => {
  const { t } = useTranslation();
  const newRights = useMemo(() => {
    return (
      rights ?? {
        roleId,
        resourceId: resource.id,
        creating: false,
        reading: false,
        updating: false,
        deleting: false,
      }
    );
  }, [rights, roleId, resource]);

  return (
    <FormControl sx={{ my: 1, mr: 3 }} component="fieldset" variant="standard">
      <FormLabel component="legend">{resource.name}</FormLabel>
      <FormGroup>
        <FormCheckbox
          labelProps={{ label: t("create") }}
          name="create[]"
          value="create"
          checked={rights?.creating || false}
          onChange={() =>
            onUpdate({ ...newRights, creating: !newRights.creating })
          }
        />
        <FormCheckbox
          labelProps={{ label: t("read") }}
          name="read[]"
          value="read"
          checked={rights?.reading || false}
          onChange={() =>
            onUpdate({ ...newRights, reading: !newRights.reading })
          }
        />
        <FormCheckbox
          labelProps={{ label: t("update") }}
          name="update[]"
          value="update"
          checked={rights?.updating || false}
          onChange={() =>
            onUpdate({ ...newRights, updating: !newRights.updating })
          }
        />
        <FormCheckbox
          labelProps={{ label: t("delete") }}
          name="delete[]"
          value="delete"
          checked={rights?.deleting || false}
          onChange={() =>
            onUpdate({ ...newRights, deleting: !newRights.deleting })
          }
        />
      </FormGroup>
      <FormHelperText sx={{ maxWidth: 300 }}>
        {resource.description}
      </FormHelperText>
    </FormControl>
  );
};

// apps/frontend/panel-vue/app/components/entities/resource/ResourceRights.vue
<script setup lang="ts">
const { roleId, resource, rights } = defineProps<{
  roleId: string
  resource: IResource
  rights?: IRights
}>()
const emit = defineEmits<{
  update: [value: IRights]
}>()

const newRights = computed(() => rights ?? {
  roleId,
  resourceId: resource.id,
  creating: false,
  reading: false,
  updating: false,
  deleting: false,
})
</script>

<template>
  <fieldset class="fieldset mr-6">
    <v-card-subtitle
      class="px-0 pt-0 pb-3"
      tag="legend"
    >
      {{ resource.name }}
    </v-card-subtitle>
    <v-card-text
      class="px-0 pt-0 pb-3"
      tag="legend"
    >
      {{ resource.description }}
    </v-card-text>
    <FormCheckbox
      :label="$t('create')"
      :model-value="newRights.creating"
      :name="`${resource.name}.creating`"
      @update:model-value="emit('update', { ...newRights, creating: Boolean($event) })"
    />
    <FormCheckbox
      :label="$t('read')"
      :model-value="newRights.reading"
      :name="`${resource.name}.reading`"
      @update:model-value="emit('update', { ...newRights, reading: Boolean($event) })"
    />
    <FormCheckbox
      :label="$t('update')"
      :model-value="newRights.updating"
      :name="`${resource.name}.updating`"
      @update:model-value="emit('update', { ...newRights, updating: Boolean($event) })"
    />
    <FormCheckbox
      :label="$t('delete')"
      :model-value="newRights.deleting"
      :name="`${resource.name}.deleting`"
      @update:model-value="emit('update', { ...newRights, deleting: Boolean($event) })"
    />
  </fieldset>
</template>

<style scoped lang="scss">
.fieldset {
  border-style: unset;
}
</style>
