// apps/frontend/panel-react/src/features/users/UserCreate.tsx
import { FC } from "react";
import { useTranslation } from "react-i18next";

import { useRights } from "@/shared/hooks/useRights";
import { getErrorText, IUser, TUserCreate } from "@workspace/shared";
import { UserForm } from "@/entities/user/UserForm";
import { useCreateUserMutation } from "./mutations";
import { useAlertsStore } from "@/shared/model/useAlertsStore";
import { ROUTES } from "@workspace/shared";

export const UserCreate: FC<{ onCreate?: (data: IUser) => void }> = ({
  onCreate,
}) => {
  const { t, i18n } = useTranslation();
  const createUser = useCreateUserMutation();
  const rights = useRights(ROUTES.api.users._);
  const addAlert = useAlertsStore((s) => s.addAlert);

  const handleCreate = (fields: TUserCreate) => {
    createUser.mutate(fields, {
      onSuccess: (data) => {
        addAlert({ type: "success", text: t("success") });
        onCreate?.(data);
      },
      onError: (error) =>
        addAlert({
          type: "error",
          text: getErrorText(error, i18n.language),
        }),
    });
  };

  return (
    <UserForm
      onCreate={handleCreate}
      createDisabled={!rights.creating}
      createLoading={createUser.isPending || Boolean(createUser.data)}
    />
  );
};

// apps/frontend/panel-vue/app/components/features/users/UserCreate.vue
<script setup lang="ts">
import usersApi from '~/components/entities/user/usersApi'

const emit = defineEmits<{
  create: [value: IUser]
}>()

const { t, locale } = useI18n()
const newData = ref<TUserCreate>({
  email: '',
  password: '',
  name: '',
})
const { data, error, execute, status } = usersApi.create(newData)
const alertsStore = useAlertsStore()
const rights = useRights(ROUTES.api.users._)

watch(data, () => {
  if (data.value) {
    alertsStore.addAlert({ type: 'success', text: t('success') })
    emit('create', data.value)
  }
})

watch(error, () => {
  if (error.value) {
    alertsStore.addAlert({
      type: 'error',
      text: getErrorText(error.value, locale.value),
    })
  }
})
</script>

<template>
  <UserForm
    create-show
    :create-disabled="!rights.creating"
    :create-loading="status === 'pending' || Boolean(data)"
    @create="(fields) => {
      newData = fields
      execute()
    }"
  />
</template>
